const express = require('express');
const especialidadController = require('../controllers/especialidadController.js');
const router = express.Router();
router.get('/', especialidadController.getAll);
router.get('/buscar/:nombre', especialidadController.buscarPorNombre);
router.get('/:id', especialidadController.getById);
router.post('/', especialidadController.create);
router.put('/:id', especialidadController.update);
router.delete('/:id', especialidadController.delete);
module.exports = router;