const express = require('express');
const medicoController = require('../controllers/medicoController.js');
const router = express.Router();
router.get('/', medicoController.getAll);
router.get('/especialidad/:especialidadId', medicoController.getByEspecialidad);
router.get('/:id', medicoController.getById);
router.get('/:id/citas', medicoController.getCitas);
router.post('/', medicoController.create);
router.put('/:id', medicoController.update);
router.delete('/:id', medicoController.delete);
module.exports = router;