const express = require('express');
const pacienteController = require('../controllers/pacienteController.js');
const router = express.Router();
router.get('/', pacienteController.getAll);
router.get('/historia/:numeroHistoria', pacienteController.getByHistoriaClinica);
router.get('/:id', pacienteController.getById);
router.post('/', pacienteController.create);
router.put('/:id', pacienteController.update);
router.delete('/:id', pacienteController.delete);
router.get('/:id/citas', pacienteController.getCitas);
module.exports = router;